services:
  - type: web
    name: dasgata
    env: docker
    plan: free
    region: oregon
    branch: master
    healthCheckPath: /health
    envVars:
      - key: DENO_DEPLOYMENT_ID
        sync: false
      - key: LAUNCHDARKLY_SDK_KEY
        sync: false
      - key: LAUNCHDARKLY_CLIENT_ID
        sync: false
      - key: MOTHERDUCK_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: false # We trigger this via GitHub Actions for better control
