# .github/workflows/launchdarkly-code-refs.yml
name: LaunchDarkly Code References

on:
  push:
    branches: [main, staging]
  pull_request:

jobs:
  find-code-references:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: LaunchDarkly Code References
        uses: launchdarkly/find-code-references@v2.12.0
        with:
          accessToken: ${{ secrets.LAUNCHDARKLY_ACCESS_TOKEN }}
          projKey: ${{ vars.LAUNCHDARKLY_PROJECT_KEY }}
          repoName: thedenogatar
          defaultBranch: main
          
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-references
          path: coderefs.json